
import __ASTRO_IMAGE_IMPORT_1uqo74 from "../../assets/images/posts/post1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2FEstren%CC%83imiento+Cro%CC%81nico+Infantil.md";
import __ASTRO_IMAGE_IMPORT_Z2jC2LR from "../../assets/images/posts/post10.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2FDesparasitacio%CC%81n+Infantil.md";
import __ASTRO_IMAGE_IMPORT_Zo4C7M from "../../assets/images/posts/post2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2FReflujo+vs+Buches+Normales.md";
import __ASTRO_IMAGE_IMPORT_nNyaD from "../../assets/images/posts/post3.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2FAlerta+de+Alergia+APLV.md";
import __ASTRO_IMAGE_IMPORT_25KedH from "../../assets/images/posts/post4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2FDolor+Abdominal+Recurrente.md";
import __ASTRO_IMAGE_IMPORT_Ltwrv from "../../assets/images/posts/post5.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2FSangre+en+las+Heces.md";
import __ASTRO_IMAGE_IMPORT_ZnMdqE from "../../assets/images/posts/post6.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2FDiarrea+Persistente.md";
import __ASTRO_IMAGE_IMPORT_ZJ0UEY from "../../assets/images/posts/post7.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2FPoco+Aumento+de+Peso.md";
import __ASTRO_IMAGE_IMPORT_24OVOB from "../../assets/images/posts/post8.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2FCo%CC%81licos+Severos.md";
import __ASTRO_IMAGE_IMPORT_105S7q from "../../assets/images/posts/post9.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2FTransicio%CC%81n+a+Alimentacio%CC%81n+Complementaria.md";
export default new Map([["../../assets/images/posts/post1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2FEstren%CC%83imiento+Cro%CC%81nico+Infantil.md", __ASTRO_IMAGE_IMPORT_1uqo74], ["../../assets/images/posts/post10.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2FDesparasitacio%CC%81n+Infantil.md", __ASTRO_IMAGE_IMPORT_Z2jC2LR], ["../../assets/images/posts/post2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2FReflujo+vs+Buches+Normales.md", __ASTRO_IMAGE_IMPORT_Zo4C7M], ["../../assets/images/posts/post3.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2FAlerta+de+Alergia+APLV.md", __ASTRO_IMAGE_IMPORT_nNyaD], ["../../assets/images/posts/post4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2FDolor+Abdominal+Recurrente.md", __ASTRO_IMAGE_IMPORT_25KedH], ["../../assets/images/posts/post5.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2FSangre+en+las+Heces.md", __ASTRO_IMAGE_IMPORT_Ltwrv], ["../../assets/images/posts/post6.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2FDiarrea+Persistente.md", __ASTRO_IMAGE_IMPORT_ZnMdqE], ["../../assets/images/posts/post7.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2FPoco+Aumento+de+Peso.md", __ASTRO_IMAGE_IMPORT_ZJ0UEY], ["../../assets/images/posts/post8.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2FCo%CC%81licos+Severos.md", __ASTRO_IMAGE_IMPORT_24OVOB], ["../../assets/images/posts/post9.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2FTransicio%CC%81n+a+Alimentacio%CC%81n+Complementaria.md", __ASTRO_IMAGE_IMPORT_105S7q]]);
		