backend:
  name: github
  repo: cesarleyto/draaniracastro
  branch: main

locale: 'es'

# Aquí definimos la carpeta de imágenes que creaste
media_folder: "public/images/post"
public_folder: "/images/post"

collections:
  - name: "blog"
    label: "Artículos (Blog)"
    folder: "src/content/blog" # (Ajustaremos esto si tus archivos .md están en otro lado)
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha", name: "pubDate", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false }
      - { label: "Categoría", name: "category", widget: "select", options: ["Síntomas", "Diagnósticos", "Vida Académica", "Testimonios"] }
      - { label: "Extracto (Resumen)", name: "excerpt", widget: "text" }
      - { label: "Imagen de Portada", name: "image", widget: "image" }
      - { label: "Cuerpo del Artículo", name: "body", widget: "markdown" }